name: Get Citation Data

on:
 schedule:
  - cron: '0 8 */3 * *'
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
        
    - name: Run
      run: |
        pip3 install -r google_scholar_crawler/requirements.txt
        python3 google_scholar_crawler/main.py
        
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        
        git add google-scholar-stats/*.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Updated Citation Data" && git push)
